### ISSUE TITLE
IPAddress Resolvers Return Error on Empty String

### ISSUE THREAD

**Issue by bbernays** [cloudquery/cq-provider-sdk#338] opened 2022-06-14 17:09 UTC
### Describe the bug

Some providers will return an empty string or nil pointer for an IP address in some cases. The SDK IP resolver returns an error when that occurs

### Expected Behavior

Should return nil/empty string if this occurs

### Steps to Reproduce

Provide an empty string to resolver

### Provider and CloudQuery version

all

**Comment by erezrokah** [comment] 2022-06-14 19:15
Can you add your use case to https://github.com/cloudquery/cq-provider-sdk/issues/327?
I only saw this for the GCP provider, so if exists on others we should change the SDK

**Comment by erezrokah** [comment] 2022-06-15 06:03
Closing in favor of https://github.com/cloudquery/cq-provider-sdk/issues/327. If I got this wrong and this issue is not a duplicate of https://github.com/cloudquery/cq-provider-sdk/issues/327 please comment and I'll re-open

**Closed by erezrokah** 2022-06-15 06:03 UTC
Labels: bug
